//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RAGen.rc
//
#define IDOK                            1
#define IDCANCEL                        2
#define ID_COMPORT                      3
#define IDD_RAGEN                       102
#define IDD_RAFEATURESPAGE              103
#define IDD_RARELAYPAGE                 104
#define IDD_RACOLORSPAGE                105
#define IDD_ABOUT                       107
#define IDD_SETTINGS                    108
#define IDD_RASTDPAGE                   109
#define IDD_TESTING                     110
#define IDD_WIFI_PASSWORD               111
#define IDD_MEMORY                      112
#define IDD_RACONTROLLER                113
#define IDB_CB_BANNER                   120
#define IDB_REEFANGEL_LOGO              121
#define IDR_ICON_MAIN                   128
#define IDR_MENU_MAIN                   129
#define IDR_MENU_RESET                  130
#define IDR_MENU_PDE_RESET              131
#define IDS_FEATURES_TAB                132
#define IDS_PDE_TAB                     133
#define IDS_COLORS_TAB                  134
#define IDS_MEMORY_TAB                  135
#define IDS_STD_TAB                     136
#define IDS_SUCCESS_GENERATE            137
#define IDS_SUCCESS_COLORS              140
#define IDS_REGISTRY_CB                 142
#define IDS_REGISTRY_RA                 143
#define IDS_ENABLE_ADVANCED             144
#define IDS_DISABLE_ADVANCED            145
#define IDS_RESET_MENU                  146
#define IDS_REGISTRY_CB_PATH            147
#define IDS_REGISTRY_RA_PATH            148
#define IDS_COMPORT                     149
#define IDS_WEBBANNER                   150
#define IDS_WIFI_PASSWORD               151
#define IDS_CRLF                        152
#define IDS_NEWLINE                     153
#define IDS_WHITESPACE                  154
#define IDS_PDE_EXTENSION               155
#define IDS_INO_EXTENSION               156
#define IDS_NO_UNKNOWN_FEATURES         157
#define IDS_UNKNOWN_FEATURES            158
#define IDS_CONTROLLER_TAB              159
#define IDS_CONTROLLER_TIPS             160
#define IDS_PORTAL						161
#define IDC_CONTROLLER_TITLE            201
#define IDS_FEATURES_DISPLAYIMAGES      202
#define IDS_FEATURES_SETUPEXTRAS        203
#define IDS_FEATURES_OVERHEATSETUP      206
#define IDS_FEATURES_DATETIMESETUP      207
#define IDS_FEATURES_VERSIONMENU        208
#define IDS_FEATURES_DIRECTTEMPSENSOR   211
#define IDS_FEATURES_WIFI               212
#define IDS_FEATURES_DISPLAYLEDPWM      213
#define IDS_FEATURES_REMOVEALLLIGHTS    215
#define IDS_FEATURES_SAVERELAYSTATE     217
#define IDS_FEATURES_EXPANSIONMODULE    218
#define IDS_FEATURES_DOSINGINTERVALSETUP 219
#define IDS_FEATURES_ATOLOGGING         220
#define IDS_FEATURES_EXCEEDFLAG         221
#define IDS_FEATURES_WDT                222
#define IDS_FEATURES_CUSTOMMENU         223
#define IDS_FEATURES_SIMPLEMENU         224
#define IDS_FEATURES_CUSTOMMAIN         225
#define IDS_FEATURES_COLORSPDE          226
#define IDS_FEATURES_PWMEXPANSION       227
#define IDS_FEATURES_FONT_8X8           228
#define IDS_FEATURES_FONT_8X16          229
#define IDS_FEATURES_FONT_12X16         230
#define IDS_FEATURES_NUMBERS_8X8        231
#define IDS_FEATURES_NUMBERS_8X16       232
#define IDS_FEATURES_NUMBERS_12X16      233
#define IDS_FEATURES_NUMBERS_16X16      234
#define IDS_FEATURES_SALINITY           235
#define IDS_FEATURES_RF                 236
#define IDS_FEATURES_AILED              237
#define IDS_FEATURES_ORP                238
#define IDS_FEATURES_IO                 239
#define IDC_RELAY_CK_FEEDING_1          300
#define IDC_RELAY_CK_FEEDING_2          301
#define IDC_RELAY_CK_FEEDING_3          302
#define IDC_RELAY_CK_FEEDING_4          303
#define IDC_RELAY_CK_FEEDING_5          304
#define IDC_RELAY_CK_FEEDING_6          305
#define IDC_RELAY_CK_FEEDING_7          306
#define IDC_RELAY_CK_FEEDING_8          307
#define IDC_RELAY_TEMP_0                308
#define IDC_RELAY_TEMP_1                309
#define IDC_RELAY_CK_WATER_1            310
#define IDC_RELAY_CK_WATER_2            311
#define IDC_RELAY_CK_WATER_3            312
#define IDC_RELAY_CK_WATER_4            313
#define IDC_RELAY_CK_WATER_5            314
#define IDC_RELAY_CK_WATER_6            315
#define IDC_RELAY_CK_WATER_7            316
#define IDC_RELAY_CK_WATER_8            317
#define IDC_RELAY_CK_OVERHEAT_1         318
#define IDC_RELAY_CK_OVERHEAT_2         319
#define IDC_RELAY_CK_OVERHEAT_3         320
#define IDC_RELAY_CK_OVERHEAT_4         321
#define IDC_RELAY_CK_OVERHEAT_5         322
#define IDC_RELAY_CK_OVERHEAT_6         323
#define IDC_RELAY_CK_OVERHEAT_7         324
#define IDC_RELAY_CK_OVERHEAT_8         325
#define IDC_RELAY_CK_LIGHTS_1           326
#define IDC_RELAY_CK_LIGHTS_2           327
#define IDC_RELAY_CK_LIGHTS_3           328
#define IDC_RELAY_CK_LIGHTS_4           329
#define IDC_RELAY_CK_LIGHTS_5           330
#define IDC_RELAY_CK_LIGHTS_6           331
#define IDC_RELAY_CK_LIGHTS_7           332
#define IDC_RELAY_CK_LIGHTS_8           333
#define IDC_RELAY_CK_ALWAYS_ON          334
#define IDC_RELAY_CK_METALHALIDES       335
#define IDC_RELAY_CK_STDLIGHTS          336
#define IDC_RELAY_CK_HEATER             337
#define IDC_RELAY_CK_CHILLER            338
#define IDC_RELAY_CK_WM1                339
#define IDC_RELAY_CK_WM2                340
#define IDC_RELAY_CK_DP1                341
#define IDC_RELAY_CK_DP2                342
#define IDC_RELAY_CK_DUALATO            343
#define IDC_RELAY_CK_SINGLEATOLOW       344
#define IDC_RELAY_CK_SINGLEATOHIGH      345
#define IDC_RELAY_CK_DELAYON            346
#define IDC_RELAY_CK_NOTUSED            347
#define IDC_RELAY_PORT_1                348
#define IDC_RELAY_PORT_2                349
#define IDC_RELAY_PORT_3                350
#define IDC_RELAY_PORT_4                351
#define IDC_RELAY_PORT_5                352
#define IDC_RELAY_PORT_6                353
#define IDC_RELAY_PORT_7                354
#define IDC_RELAY_PORT_8                355
#define IDC_RELAY_CK_LOGGING            356
#define IDC_RELAY_CK_WEB                357
#define IDC_RELAY_SPIN_DELAY_ON         358
#define IDC_RELAY_EDIT_DELAY_ON         359
#define IDC_MEMORY_GROUP_LIGHTS         400
#define IDC_MEMORY_GROUP_WAVEMAKERS     401
#define IDC_MEMORY_GROUP_DOSING_PUMPS   402
#define IDC_MEMORY_GROUP_ATO            403
#define IDC_MEMORY_GROUP_TIMEOUTS       404
#define IDC_MEMORY_GROUP_TEMPS          405
#define IDC_MEMORY_EDIT_MH_DELAY        407
#define IDC_MEMORY_EDIT_DP1_RUNTIME     408
#define IDC_MEMORY_EDIT_DP2_RUNTIME     409
#define IDC_MEMORY_EDIT_ATO_LOW_TIMEOUT 410
#define IDC_MEMORY_EDIT_ATO_HIGH_TIMEOUT 411
#define IDC_MEMORY_SPIN_MH_DELAY        412
#define IDC_MEMORY_TIME_MH_ON           413
#define IDC_MEMORY_TIME_MH_OFF          414
#define IDC_MEMORY_TIME_STD_ON          415
#define IDC_MEMORY_TIME_STD_OFF         416
#define IDC_MEMORY_EDIT_WM1_INTERVAL    417
#define IDC_MEMORY_EDIT_WM2_INTERVAL    418
#define IDC_MEMORY_CK_WM1_ALWAYS_ON     419
#define IDC_MEMORY_SPIN_WM1_INTERVAL    420
#define IDC_MEMORY_CK_WM2_ALWAYS_ON     421
#define IDC_MEMORY_SPIN_WM2_INTERVAL    422
#define IDC_MEMORY_EDIT_ACTINIC         423
#define IDC_MEMORY_EDIT_DAYLIGHT        424
#define IDC_MEMORY_TIME_DP1_ON          425
#define IDC_MEMORY_SPIN_ACTINIC         426
#define IDC_MEMORY_SPIN_DAYLIGHT        427
#define IDC_MEMORY_TIME_DP2_ON          428
#define IDC_MEMORY_SPIN_DP1_RUNTIME     429
#define IDC_MEMORY_SPIN_DP2_RUNTIME     430
#define IDC_MEMORY_EDIT_FEEDING         431
#define IDC_MEMORY_SPIN_FEEDING         432
#define IDC_MEMORY_EDIT_LCD             433
#define IDC_MEMORY_SPIN_LCD             434
#define IDC_MEMORY_EDIT_PH7             435
#define IDC_MEMORY_EDIT_PH10            436
#define IDC_MEMORY_SPIN_PH7             437
#define IDC_MEMORY_SPIN_PH10            438
#define IDC_MEMORY_CB_HEATER_ON         439
#define IDC_MEMORY_CB_HEATER_OFF        440
#define IDC_MEMORY_CB_CHILLER_ON        441
#define IDC_MEMORY_CB_CHILLER_OFF       442
#define IDC_MEMORY_CB_OVERHEAT          443
#define IDC_MEMORY_SPIN_ATO_LOW_TIMEOUT 444
#define IDC_MEMORY_SPIN_ATO_HIGH_TIMEOUT 445
#define IDC_MEMORY_EDIT_ATO_LOW_INTERVAL 446
#define IDC_MEMORY_EDIT_ATO_HIGH_INTERVAL 447
#define IDC_MEMORY_SPIN_ATO_LOW_INTERVAL 448
#define IDC_MEMORY_SPIN_ATO_HIGH_INTERVAL 449
#define IDC_MEMORY_CK_ATO_LOW_INTERVAL  450
#define IDC_MEMORY_CK_ATO_HIGH_INTERVAL 451
#define IDC_MEMORY_STATIC_FEEDING       452
#define IDC_MEMORY_STATIC_LCD           453
#define IDC_MEMORY_STATIC_PH7           454
#define IDC_MEMORY_STATIC_PH10          455
#define IDC_MEMORY_BTN_GENERATE         456
#define IDC_MEMORY_BTN_ENABLE_ADVANCED  457
#define IDC_MEMORY_STATUS               458
#define IDC_MEMORY_BTN_LAUNCH           459
#define IDC_STD_GROUP_LIGHTS            600
#define IDC_STD_GROUP_WAVEMAKERS        601
#define IDC_STD_GROUP_PORTS             602
#define IDC_STD_GROUP_ATO               603
#define IDC_STD_GROUP_TIMEOUTS          604
#define IDC_STD_GROUP_TEMPS             605
#define IDC_STD_EDIT_MH_DELAY           606
#define IDC_STD_EDIT_ATO_TIMEOUT        607
#define IDC_STD_SPIN_MH_DELAY           608
#define IDC_STD_TIME_MH_ON              609
#define IDC_STD_TIME_MH_OFF             610
#define IDC_STD_TIME_STD_ON             611
#define IDC_STD_TIME_STD_OFF            612
#define IDC_STD_EDIT_WM1_INTERVAL       613
#define IDC_STD_EDIT_WM2_INTERVAL       614
#define IDC_STD_CK_WM1_ALWAYS_ON        615
#define IDC_STD_SPIN_WM1_INTERVAL       616
#define IDC_STD_CK_WM2_ALWAYS_ON        617
#define IDC_STD_SPIN_WM2_INTERVAL       618
#define IDC_STD_EDIT_FEEDING            619
#define IDC_STD_SPIN_FEEDING            620
#define IDC_STD_EDIT_LCD                621
#define IDC_STD_SPIN_LCD                622
#define IDC_STD_CB_HEATER_ON            623
#define IDC_STD_CB_HEATER_OFF           624
#define IDC_STD_CB_CHILLER_ON           625
#define IDC_STD_CB_CHILLER_OFF          626
#define IDC_STD_CB_OVERHEAT             627
#define IDC_STD_SPIN_ATO_TIMEOUT        628
#define IDC_STD_STATIC_FEEDING          629
#define IDC_STD_STATIC_LCD              630
#define IDC_STD_CK_ATO                  631
#define IDC_STD_CK_STD_LIGHTS           632
#define IDC_STD_CK_MH_LIGHTS            633
#define IDC_STD_CK_WM2                  634
#define IDC_STD_CK_WM1                  635
#define IDC_STD_CK_CHILLER              636
#define IDC_STD_CK_HEATER               637
#define IDC_STD_CK_SUMP                 638
#define IDC_STD_TEMP_0                  639
#define IDC_STD_TEMP_1                  640
#define IDC_STD_CK_LOGGING              641
#define IDC_STD_GROUP_TEMP              642
#define IDC_STD_GROUP_LOGGING           643
#define IDC_STD_CK_WEB                  644
#define IDC_TESTING_STATUS              700
#define IDD_COM_LIST                    701
#define IDD_WEB_BANNER                  750
#define IDC_WEB_ID                      751
#define IDD_PORTAL                      751
#define IDC_WEB_T1                      752
#define IDC_WEB_T2                      753
#define IDC_WEB_T3                      754
#define IDC_WEB_R1                      755
#define IDC_WEB_R2                      756
#define IDC_WEB_R3                      757
#define IDC_WEB_R4                      758
#define IDC_WEB_R5                      759
#define IDC_WEB_R6                      760
#define IDC_WEB_R7                      761
#define IDC_WEB_R8                      762
#define IDC_WEB_EDIT_INTERVAL           763
#define IDC_WEB_SPIN_INTERVAL           764
#define IDC_WEB_BTN_QUESTION            765
#define IDC_ABOUT_TEXT_VERSION          1000
#define IDC_ABOUT_REEFANGEL_LOGO        1001
#define IDC_ABOUT_CURTBINDER_LOGO       1002
#define IDC_TAB                         1003
#define IDC_BTN_GENERATE                1004
#define IDC_TEXT_STATUS                 1005
#define IDC_SETTINGS_SKETCH_FOLDER      1006
#define IDC_SETTINGS_SKETCH_BTN_BROWSE  1007
#define IDC_SETTINGS_ARDUINO_FOLDER     1008
#define IDC_SETTINGS_ARDUINO_BTN_BROWSE 1009
#define IDC_SETTINGS_CB_REGISTRY        1010
#define IDC_SETTINGS_TEXT_REGISTRY      1011
#define IDC_SETTINGS_BTN_CLEAR          1012
#define IDC_SETTINGS_CB_LAUNCH          1013
#define IDC_SETTINGS_CB_APP_MODE        1014
#define IDC_SETTINGS_TEXT_ARDUINO       1015
#define IDC_SETTINGS_LIBRARY_FOLDER     1016
#define IDC_SETTINGS_CB_APP_MODE2       1016
#define IDC_SETTINGS_CB_DEV_LIBRARIES   1016
#define IDC_SETTINGS_LIBRARY_BTN_BROWSE 1017
#define IDC_BTN_LAUNCH                  1018
#define IDC_BTN_CLOSE                   1019
#define IDC_COM_LIST_PORTS              1020
#define IDC_PASSWORD_USERNAME           1021
#define IDC_PASSWORD_PASSWORD           1022
#define IDC_PASSWORD_SHOW               1023
#define IDC_PASSWORD_CLEAR              1024
#define IDC_EDIT_ENTRIES                1025
#define IDC_SPIN_ENTRIES                1026
#define IDC_CONTROLLER_TEMP_0           1029
#define IDC_CONTROLLER_TEMP_1           1030
#define IDC_CBO_WIFI                    1032
#define IDC_BUTTON2                     1034
#define IDC_BTN_PORTAL                  1034
#define IDC_CBO_EXP_RELAY_QTY           1035
#define IDC_CBO_PWMSLOPE                1036
#define IDC_CBO_PORTAL                  1037
#define IDC_PORTAL_USERNAME             1038
#define IDC_PORTAL_KEY                  1039
#define IDC_PORTAL_SHOW                 1040
#define IDC_PORTAL_CLEAR                1041
#define IDC_PORTAL_CLEAR_ALL            1042
#define IDC_FEATURES_TEXT_DESCRIPTION   2001
#define IDC_FEATURES_TREE               2002
#define ID_FILE_EXIT                    32771
#define ID_HELP_ABOUT                   32772
#define ID_EDIT_SETTINGS                32773
#define ID_CHANGE_MENU                  32774
#define ID_RESET_ALL                    32775
#define ID_RESET_SAVED                  32776
#define ID_RESET_PORTS                  32777
#define ID_RESET_TEMPERATURE            32778
#define ID_RESET_FEEDINGMODE            32779
#define ID_RESET_WATERCHANGEMODE        32780
#define ID_RESET_OVERHEAT               32781
#define ID_RESET_LIGHTSON               32782
#define ID_RESET_LOGGING                32783
#define ID_UPDATE_STATUS                32784
#define ID_EDIT_ENABLE_ADVANCED         32785
#define ID_FILE_RESTART                 32786
#define ID_SAVE_FEATURES                32787
#define ID_CONTROLLER_FIND              32788
#define ID_CONTROLLER_WEBBANNER         32789
#define ID_CONTROLLER_WIFIPASSWORD      32790
#define ID_CONTROLLER_IMPORTFEATURESFROMFILE 32791
#define ID_CONTROLLER_SHOWUNKNOWNFEATURES 32792
#define ID_CONTROLLER_INTERNALMEMORY    32793
#define ID_CONTROLLER_SHOWLIBRARYVERSION 32794

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        801
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1043
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
