//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RAGen.rc
//
#define IDOK                            1
#define IDCANCEL                        2
#define IDD_RAGEN                       102
#define IDD_RAFEATURESPAGE              103
#define IDD_RAPDEPAGE                   104
#define IDD_RACOLORSPAGE                105
#define IDD_RASETTINGSPAGE              106
#define IDD_ABOUT                       107
#define IDD_SETTINGS                    108
#define IDB_CURTBINDER_LOGO             120
#define IDB_REEFANGEL_LOGO              121
#define IDR_ICON_MAIN                   128
#define IDR_MENU_MAIN                   129
#define IDS_FEATURES_DISPLAYIMAGES      202
#define IDS_FEATURES_SETUPEXTRAS        203
#define IDS_FEATURES_DOSINGPUMPSETUP    204
#define IDS_FEATURES_WAVEMAKERSETUP     205
#define IDS_FEATURES_OVERHEATSETUP      206
#define IDS_FEATURES_DATETIMESETUP      207
#define IDS_FEATURES_VERSIONMENU        208
#define IDS_FEATURES_ATOSETUP           209
#define IDS_FEATURES_METALHALIDESETUP   210
#define IDS_FEATURES_DIRECTTEMPSENSOR   211
#define IDS_FEATURES_WIFI               212
#define IDS_FEATURES_DISPLAYLEDPWM      213
#define IDS_FEATURES_ALTERNATEFONT      214
#define IDS_FEATURES_REMOVEALLLIGHTS    215
#define IDS_FEATURES_STANDARDLIGHTSETUP 216
#define IDS_FEATURES_SAVERELAYSTATE     217
#define IDS_FEATURES_SINGLEATO          218
#define IDC_ABOUT_TEXT_VERSION          1000
#define IDC_ABOUT_REEFANGEL_LOGO        1001
#define IDC_ABOUT_CURTBINDER_LOGO       1002
#define IDC_FEATURES_TEXT_DESCRIPTION   2001
#define IDC_FEATURES_CK_DISPLAY_IMAGES  2002
#define IDC_FEATURES_CK_SETUP_EXTRAS    2003
#define IDC_FEATURES_CK_DOSINGPUMP_SETUP 2004
#define IDC_FEATURES_CK_WAVEMAKER_SETUP 2005
#define IDC_FEATURES_CK_SAVE_RELAY_STATE 2006
#define IDC_FEATURES_CK_OVERHEAT_SETUP  2007
#define IDC_FEATURES_CK_DATE_TIME_SETUP 2008
#define IDC_FEATURES_CK_VERSION_MENU    2009
#define IDC_FEATURES_CK_ATO_SETUP       2010
#define IDC_FEATURES_CK_METAL_HALIDE_SETUP 2011
#define IDC_FEATURES_CK_DIRECT_TEMP_SENSOR 2012
#define IDC_FEATURES_CK_DISPLAY_LED_PWM 2013
#define IDC_FEATURES_CK_WIFI            2014
#define IDC_FEATURES_CK_ALTERNATE_FONT  2015
#define IDC_FEATURES_CK_STANDARD_LIGHTS_SETUP 2016
#define IDC_FEATURES_CK_REMOVE_ALL_LIGHTS 2017
#define IDC_FEATURES_CK_SINGLE_ATO      2018
#define ID_FILE_EXIT                    32771
#define ID_HELP_ABOUT                   32772
#define ID_EDIT_SETTINGS                32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        600
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
